### ISSUE TITLE
ghc-8.4.2 Segmentation fault: Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by newhoggy** [haskell/haskell-ide-engine#562]
For a project that uses `nightly` resolver:

```
$ grep '^resolver' stack.yaml
resolver: nightly-2018-05-02
$ stack exec -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.2
```

I get the following error:

```
Using ghc version: Version 0.2.0.0, Git revision 4e900d53c401c0d3b6f69c6bbddc9ab6c6834d0d (1338 commits) x86_64 ghc-8.4.2
Using hoogle db at: /Users/jky/.hoogle/default-haskell-5.0.17.hoo
/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/hie-wrapper.sh: line 77: 73937 Segmentation fault: 11  $HIEBIN --lsp $@
[Info  - 10:04:21] Connection to server got closed. Server will restart.
[Error - 10:04:21] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/client.js:1954:42)
	at LanguageClient.handleConnectionClosed (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/main.js:126:15)
	at closeHandler (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/client.js:1941:18)
	at CallbackList.invoke (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/messageReader.js:135:27)
	at Socket.<anonymous> (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
[Error - 10:04:21] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/client.js:1954:42)
	at LanguageClient.handleConnectionClosed (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/main.js:126:15)
	at closeHandler (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-languageclient/lib/client.js:1941:18)
	at CallbackList.invoke (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at StreamMessageReader.AbstractMessageReader.fireClose (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/messageReader.js:135:27)
	at Socket.<anonymous> (/Users/jky/.vscode/extensions/alanz.vscode-hie-server-0.0.16/node_modules/vscode-jsonrpc/lib/messageReader.js:188:62)
	at emitOne (events.js:101:20)
	at Socket.emit (events.js:191:7)
	at Pipe._handle.close [as _onclose] (net.js:510:12)
Using ghc version: Version 0.2.0.0, Git revision 4e900d53c401c0d3b6f69c6bbddc9ab6c6834d0d (1338 commits) x86_64 ghc-8.4.2
Using hoogle db at: /Users/jky/.hoogle/default-haskell-5.0.17.hoo
hie: 
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/jky/.stack/programs/x86_64-osx/ghc-8.4.2/lib/ghc-8.4.2/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o: unknown symbol `___gmp_rands'
[Error - 10:04:22] Got error while processing diagnostics: unable to load package `integer-gmp-1.0.2.0'
```

**Comment by Bubba** [comment]
I'm seeing this as well for the integer-gmp package, before any requests are made.

**Comment by Bubba** [comment]
Did you install ghc via homebrew? Reinstalling gmp did the trick for me: `brew reinstall gmp`

**Comment by newhoggy** [comment]
Wow, that fixed my problem.  Nice!  Thanks!

```
$ brew reinstall gmp
==> Reinstalling gmp
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_2.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gmp-6.1.2_2.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.1.2_2: 18 files, 3.1MB
```

**Comment by newhoggy** [comment]
Actually, I'm still getting this error:

```
Using ghc version: Version 0.2.0.0, Git revision 4e900d53c401c0d3b6f69c6bbddc9ab6c6834d0d (1338 commits) x86_64 ghc-8.4.2
Using hoogle db at: /Users/jky/.hoogle/default-haskell-5.0.17.hoo
hie: 
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/jky/.stack/programs/x86_64-osx/ghc-8.4.2/lib/ghc-8.4.2/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o: unknown symbol `___gmp_rands'
[Error - 23:52:47] Got error while processing diagnostics: unable to load package `integer-gmp-1.0.2.0'
[Error - 23:52:56] Got error while processing diagnostics: GHC panic! (the 'impossible' happened)
  ghc-mod version 5.9.0.0
  GHC library version 8.4.2 for x86_64-apple-darwin:
       Dynamic linker not initialised

Please report this as a bug: https://github.com/kazu-yamamoto/ghc-mod/issues
```

**Comment by Bubba** [comment]
@newhoggy unbelievably, someone found a workaround here https://github.com/haskell/haddock/issues/767
I just renamed the file to something else and it works for me!

**Comment by alanz** [comment]
@newhoggy please close this if it is resolved

**Comment by newhoggy** [comment]
I'd like to confirm that it is fixed.  Thanks so much!

**Comment by Bubba** [comment]
The problem has reappeared for me on `c34c08eeced8173983601e98304258075f3057e1` and ghc 8.4.3:

```
info: Found Stack project at: /Users/luke/Sources/haskell-ide-engine
Using hie version: Version 0.2.0.0, Git revision c34c08eeced8173983601e98304258075f3057e1 (1459 commits) x86_64 ghc-8.4.3
info: Using Stack project at: /Users/luke/Sources/haskell-ide-engine
Using hoogle db at: /Users/luke/.hoogle/default-haskell-5.0.17.hoo
info: Found Stack project at: /Users/luke/Sources/haskell-ide-engine
info: Using Stack project at: /Users/luke/Sources/haskell-ide-engine
DEBUG: reading cache: /Users/luke/Sources/haskell-ide-engine/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.cabal-components
DEBUG: regenerating cache: /Users/luke/Sources/haskell-ide-engine/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.cabal-components (input data changed)
DEBUG: writing memory cache: /Users/luke/Sources/haskell-ide-engine/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.cabal-components
DEBUG: resolveEntrypoint:
       ["-i","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build","-isrc","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h"]
DEBUG: resolveEntrypoint:
       ["-i","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/hie-tmp","-iapp","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/hie-tmp","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen/cabal_macros.h"]
DEBUG: resolveEntrypoint: []
DEBUG: making sure autogen files exist
DEBUG: reading cache: .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.resolved-components
DEBUG: resolvedComponentsCache: files changed: none
DEBUG: resolveGmComponent:
       ["-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h"]
DEBUG: resolveGmComponent:
       ["-i","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/hie-tmp","-iapp","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/hie-tmp","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen/cabal_macros.h","-XHaskell2010","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h"]
DEBUG: resolveGmComponent:
       ["-i","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build","-isrc","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h","-XHaskell2010","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h"]
DEBUG: regenerating cache: .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.resolved-components (input data changed)
DEBUG: writing memory cache: .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.resolved-components
VOMIT: Using the following mapped files: "/Users/luke/Sources/haskell-ide-engine/src/Haskell/Ide/Engine/Transport/LspStdio.hs"
VOMIT: Initializing GHC session with following options: "-fbuilding-cabal-package" "-O" "-outputdir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-odir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-hidir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-stubdir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-i" "-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-isrc" "-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen" "-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen" "-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen" "-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen" "-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-optP-include" "-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h" "-this-unit-id" "haskell-ide-engine-0.2.0.0-7HZrGfRRjONEXbBFqqpRFd" "-hide-all-packages" "-Wmissing-home-modules" "-no-user-package-db" "-package-db" "/Users/luke/.stack/snapshots/x86_64-osx/nightly-2018-06-02/8.4.3/pkgdb" "-package-db" "/Users/luke/Sources/haskell-ide-engine/.stack-work/install/x86_64-osx/nightly-2018-06-02/8.4.3/pkgdb" "-package-id" "Cabal-2.2.0.1" "-package-id" "Diff-0.3.4-2nHlmnArMpA8s1ZgPQDn29" "-package-id" "HaRe-0.8.4.1-Bcgf0n7r4Zp2r1svuQoah1" "-package-id" "aeson-1.3.1.1-Gvb6pihaaEVBNfNP5X991Q" "-package-id" "apply-refact-0.5.0.0-Hz2HRMUSWXmIkWS5Y7q3lw" "-package-id" "async-2.2.1-1bsiEsDyYvD1Jx6uPPJyV0" "-package-id" "base-4.11.1.0" "-package-id" "brittany-0.11.0.0-DeYoqyPRMVe6Fh5MUSWYFx" "-package-id" "bytestring-0.10.8.2" "-package-id" "cabal-helper-0.8.0.3-LSXbbKxgBGZIzYM0wEoi0j" "-package-id" "containers-0.5.11.0" "-package-id" "data-default-0.7.1.1-HjQKn6Xjs875aCLGpDUtkz" "-package-id" "directory-1.3.1.5" "-package-id" "extra-1.6.8-2KHLwinC2i1KygJvweFKV" "-package-id" "filepath-1.4.2" "-package-id" "ghc-8.4.3" "-package-id" "ghc-exactprint-0.5.6.1-IIyrgrgUyhcHDlDtqBSqlv" "-package-id" "ghc-mod-5.9.0.0-KgvNHgQGqyWEDYph2ea2hO" "-package-id" "ghc-mod-core-5.9.0.0-FNjyzKOYwILHhmM91YPoiu" "-package-id" "gitrev-1.3.1-GWZebipuES31VlD8DlE6Dn" "-package-id" "haddock-api-2.20.0-IqfPIVGGL2nIDthcZAQjoB" "-package-id" "haddock-library-1.6.0-L6hJwhF0IIi3ImNW1ARDmy" "-package-id" "haskell-lsp-0.2.2.0-KLmD30grNuJ2bKIIXm8a" "-package-id" "haskell-src-exts-1.20.2-66wmDqusNtt2tejiOeCDMY" "-package-id" "hie-plugin-api-0.2.0.0-HJ99rwSDeja4UBWGjVCCaJ" "-package-id" "hlint-2.1.5-34HXQ4Am32YAZTLyc2F8Rs" "-package-id" "hoogle-5.0.17.3-7BducjVMdSiBXuaunws1Mj" "-package-id" "hslogger-1.2.10-8TR0kRq9cFG7IbKu4YGix" "-package-id" "lens-4.16.1-3qnn5SmfGVTE135hKKD4FZ" "-package-id" "monad-control-1.0.2.3-4Xb5iIxO4VM2FVnddKC6of" "-package-id" "monoid-subclasses-0.4.6-lUJd5M6Kve6K9XIuEJRdY" "-package-id" "mtl-2.2.2" "-package-id" "optparse-simple-0.1.0-7PWoKTgUsxi3HXss1HbZlB" "-package-id" "process-1.6.3.0" "-package-id" "sorted-list-0.2.1.0-1TWUqAXflzVD3kKmNlssKY" "-package-id" "stm-2.4.5.0" "-package-id" "tagsoup-0.14.6-OPbG69Fjej12z5OqNrWA4" "-package-id" "text-1.2.3.0" "-package-id" "transformers-0.5.5.0" "-package-id" "vector-0.12.0.1-4awQG9XUvVEBfJgKGHBhOb" "-package-id" "yaml-0.8.30-DDs3nB8v2ap48JqXiiKzVi" "-package-id" "yi-rope-0.10-BdvTGgtdCzpArPnoCMA2fe" "-XHaskell2010" "-Wall" "-Wredundant-constraints" "-Werror" "-Wno-missing-home-modules" "-O0" "-fno-warn-missing-home-modules"
DEBUG: initSession: Session not initialized, creating new one
VOMIT: Using the following targets: "/Users/luke/Sources/haskell-ide-engine/src/Haskell/Ide/Engine/Transport/LspStdio.hs" "/Users/luke/Sources/haskell-ide-engine/src/Haskell/Ide/Engine/Transport/LspStdio.hs"
DEBUG: loadTargets:
       Loading: /private/var/folders/m7/r7ds62j90sl5vt4phwsnfv2w0000gp/T/ghc-mod9858/LspStdio9857-0.hs
DEBUG: loadTargets: filterModSums: True
info: loadTargets:
      Target needs interpeter, switching to LinkInMemory/HscInterpreted. Perfectly normal if anything is using TemplateHaskell, QuasiQuotes or PatternSynonyms.
/Users/luke/.vscode/extensions/alanz.vscode-hie-server-0.0.19/hie-vscode.sh: line 12:  9857 Segmentation fault: 11  hie --lsp $@
[Info  - 12:07:47] Connection to server got closed. Server will restart.
info: Found Stack project at: /Users/luke/Sources/haskell-ide-engine
Using hie version: Version 0.2.0.0, Git revision c34c08eeced8173983601e98304258075f3057e1 (1459 commits) x86_64 ghc-8.4.3
info: Using Stack project at: /Users/luke/Sources/haskell-ide-engine
Using hoogle db at: /Users/luke/.hoogle/default-haskell-5.0.17.hoo
info: Found Stack project at: /Users/luke/Sources/haskell-ide-engine
info: Using Stack project at: /Users/luke/Sources/haskell-ide-engine
DEBUG: reading cache: /Users/luke/Sources/haskell-ide-engine/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.cabal-components
DEBUG: resolveEntrypoint:
       ["-i","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build","-isrc","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h"]
DEBUG: resolveEntrypoint:
       ["-i","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/hie-tmp","-iapp","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen","-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen","-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/hie-tmp","-optP-include","-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/hie/autogen/cabal_macros.h"]
DEBUG: resolveEntrypoint: []
DEBUG: making sure autogen files exist
DEBUG: reading cache: .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup-config.ghc-mod.resolved-components
VOMIT: Using the following mapped files: "/Users/luke/Sources/haskell-ide-engine/src/Haskell/Ide/Engine/Transport/LspStdio.hs"
VOMIT: Initializing GHC session with following options: "-fbuilding-cabal-package" "-O" "-outputdir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-odir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-hidir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-stubdir" ".stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-i" "-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-isrc" "-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen" "-i.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen" "-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen" "-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/global-autogen" "-I.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build" "-optP-include" "-optP.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/autogen/cabal_macros.h" "-this-unit-id" "haskell-ide-engine-0.2.0.0-7HZrGfRRjONEXbBFqqpRFd" "-hide-all-packages" "-Wmissing-home-modules" "-no-user-package-db" "-package-db" "/Users/luke/.stack/snapshots/x86_64-osx/nightly-2018-06-02/8.4.3/pkgdb" "-package-db" "/Users/luke/Sources/haskell-ide-engine/.stack-work/install/x86_64-osx/nightly-2018-06-02/8.4.3/pkgdb" "-package-id" "Cabal-2.2.0.1" "-package-id" "Diff-0.3.4-2nHlmnArMpA8s1ZgPQDn29" "-package-id" "HaRe-0.8.4.1-Bcgf0n7r4Zp2r1svuQoah1" "-package-id" "aeson-1.3.1.1-Gvb6pihaaEVBNfNP5X991Q" "-package-id" "apply-refact-0.5.0.0-Hz2HRMUSWXmIkWS5Y7q3lw" "-package-id" "async-2.2.1-1bsiEsDyYvD1Jx6uPPJyV0" "-package-id" "base-4.11.1.0" "-package-id" "brittany-0.11.0.0-DeYoqyPRMVe6Fh5MUSWYFx" "-package-id" "bytestring-0.10.8.2" "-package-id" "cabal-helper-0.8.0.3-LSXbbKxgBGZIzYM0wEoi0j" "-package-id" "containers-0.5.11.0" "-package-id" "data-default-0.7.1.1-HjQKn6Xjs875aCLGpDUtkz" "-package-id" "directory-1.3.1.5" "-package-id" "extra-1.6.8-2KHLwinC2i1KygJvweFKV" "-package-id" "filepath-1.4.2" "-package-id" "ghc-8.4.3" "-package-id" "ghc-exactprint-0.5.6.1-IIyrgrgUyhcHDlDtqBSqlv" "-package-id" "ghc-mod-5.9.0.0-KgvNHgQGqyWEDYph2ea2hO" "-package-id" "ghc-mod-core-5.9.0.0-FNjyzKOYwILHhmM91YPoiu" "-package-id" "gitrev-1.3.1-GWZebipuES31VlD8DlE6Dn" "-package-id" "haddock-api-2.20.0-IqfPIVGGL2nIDthcZAQjoB" "-package-id" "haddock-library-1.6.0-L6hJwhF0IIi3ImNW1ARDmy" "-package-id" "haskell-lsp-0.2.2.0-KLmD30grNuJ2bKIIXm8a" "-package-id" "haskell-src-exts-1.20.2-66wmDqusNtt2tejiOeCDMY" "-package-id" "hie-plugin-api-0.2.0.0-HJ99rwSDeja4UBWGjVCCaJ" "-package-id" "hlint-2.1.5-34HXQ4Am32YAZTLyc2F8Rs" "-package-id" "hoogle-5.0.17.3-7BducjVMdSiBXuaunws1Mj" "-package-id" "hslogger-1.2.10-8TR0kRq9cFG7IbKu4YGix" "-package-id" "lens-4.16.1-3qnn5SmfGVTE135hKKD4FZ" "-package-id" "monad-control-1.0.2.3-4Xb5iIxO4VM2FVnddKC6of" "-package-id" "monoid-subclasses-0.4.6-lUJd5M6Kve6K9XIuEJRdY" "-package-id" "mtl-2.2.2" "-package-id" "optparse-simple-0.1.0-7PWoKTgUsxi3HXss1HbZlB" "-package-id" "process-1.6.3.0" "-package-id" "sorted-list-0.2.1.0-1TWUqAXflzVD3kKmNlssKY" "-package-id" "stm-2.4.5.0" "-package-id" "tagsoup-0.14.6-OPbG69Fjej12z5OqNrWA4" "-package-id" "text-1.2.3.0" "-package-id" "transformers-0.5.5.0" "-package-id" "vector-0.12.0.1-4awQG9XUvVEBfJgKGHBhOb" "-package-id" "yaml-0.8.30-DDs3nB8v2ap48JqXiiKzVi" "-package-id" "yi-rope-0.10-BdvTGgtdCzpArPnoCMA2fe" "-XHaskell2010" "-Wall" "-Wredundant-constraints" "-Werror" "-Wno-missing-home-modules" "-O0" "-fno-warn-missing-home-modules"
DEBUG: initSession: Session not initialized, creating new one
VOMIT: Using the following targets: "/Users/luke/Sources/haskell-ide-engine/src/Haskell/Ide/Engine/Transport/LspStdio.hs" "/Users/luke/Sources/haskell-ide-engine/src/Haskell/Ide/Engine/Transport/LspStdio.hs"
DEBUG: loadTargets:
       Loading: /private/var/folders/m7/r7ds62j90sl5vt4phwsnfv2w0000gp/T/ghc-mod10139/LspStdio10138-0.hs
DEBUG: loadTargets: filterModSums: True
info: loadTargets:
      Target needs interpeter, switching to LinkInMemory/HscInterpreted. Perfectly normal if anything is using TemplateHaskell, QuasiQuotes or PatternSynonyms.
hie: 
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/luke/.stack/programs/x86_64-osx/ghc-8.4.3/lib/ghc-8.4.3/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o: unknown symbol `___gmp_rands'
```

But renaming that file still fixes it.

**Comment by LeanderK** [comment]
this problem also appeared for me, maybe it should be noted somewhere
