### ISSUE TITLE
Type information on hover is unavailable

### ISSUE THREAD

**Issue by mrkafk** [haskell/haskell-ide-engine#854]
It's hanging there forever with `Loading...`:

![hie_hover](https://user-images.githubusercontent.com/593219/46500759-e23f2600-c823-11e8-9080-a4fad879f9b3.png)

`renderer1.log` contains

```
[2018-10-04 22:11:14.012] [renderer1] [error] Error: No hints: Error: Error: No hints
        at /home/mark/.vscode/extensions/alanz.vscode-hie-server-0.0.24/out/src/commands/showType.js:38:19
        at Generator.next (<anonymous>)
        at fulfilled (/home/mark/.vscode/extensions/alanz.vscode-hie-server-0.0.24/out/src/commands/showType.js:4:58)
        at <anonymous>
```

HIE seems to start  from project's directory OK:

```
mark@titan ~/haskell/h4 % /home/mark/projects/components/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-12.8/8.4.3/bin/hie
2018-10-04 22:24:18.782715979 [ThreadId 4] - Using stack GHC version
2018-10-04 22:24:18.917808863 [ThreadId 4] - Run entered for HIE(hie) Version 0.2.2.0, Git revision 881f2b3b737c34f72fffa3bec94f08f256f0d6fe (2000 commits) x86_64 ghc-8.4.3
2018-10-04 22:24:18.918874481 [ThreadId 4] - Current directory:/home/mark/haskell/h4
```

**Comment by mrkafk** [comment]
False alarm. I've done `stack build cabal-install` in project folder since I did not want to install it globally. After `stack install cabal-install` and then update it works.
